"""Generate markdown API documentation from a .pyi type stub.

Usage:
    python tools/generate_api_docs.py --stub docs/uefn_stub.pyi
    python tools/generate_api_docs.py --stub docs/uefn_stub.pyi --output docs/generated

Parses the .pyi stub generated by generate_uefn_stub.py and produces
organized markdown documentation files in docs/generated/.
"""

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class Member:
    name: str
    kind: str  # "property", "method", "enum_value"
    signature: str = ""
    return_type: str = ""
    description: str = ""
    value: str = ""  # for enum members


@dataclass
class TypeInfo:
    name: str
    kind: str  # "class", "struct", "enum", "function"
    base: str = ""
    docstring: str = ""
    members: List[Member] = field(default_factory=list)
    module: str = ""  # C++ source module if available


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------


def parse_stub(path: str) -> Tuple[List[TypeInfo], Dict[str, str]]:
    """Parse a .pyi stub file into a list of TypeInfo objects.

    Returns (types, metadata) where metadata has header stats.
    """
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    types: List[TypeInfo] = []
    metadata: Dict[str, str] = {}
    current_section = ""

    # Parse header comments for metadata
    for line in lines[:10]:
        if line.startswith("# Types:"):
            metadata["types_summary"] = line[2:].strip()
        elif line.startswith("# Auto-generated"):
            metadata["source"] = line[2:].strip()

    i = 0
    while i < len(lines):
        line = lines[i]

        # Track section headers
        if line.startswith("# ==="):
            if i + 1 < len(lines):
                section_line = lines[i + 1].strip("# ").strip()
                if section_line.startswith("Top-level"):
                    current_section = "function"
                elif section_line.startswith("Enum"):
                    current_section = "enum"
                elif section_line.startswith("Struct"):
                    current_section = "struct"
                elif section_line.startswith("Class"):
                    current_section = "class"
            i += 1
            continue

        # Top-level function
        if current_section == "function" and line.startswith("def "):
            info = _parse_function(line)
            if info:
                types.append(info)
            i += 1
            continue

        # Class/struct/enum definition
        if line.startswith("class "):
            info, i = _parse_class(lines, i, current_section)
            if info:
                types.append(info)
            continue

        i += 1

    return types, metadata


def _parse_function(line: str) -> Optional[TypeInfo]:
    """Parse a top-level function line like: def name(args) -> Type: ...  # desc"""
    m = re.match(r"def (\w+)(\(.*?\))(?:\s*->.*?)?: \.\.\.(?:\s*#\s*(.*))?", line)
    if not m:
        # Try simpler pattern
        m = re.match(r"def (\w+)(\(.*)", line)
        if not m:
            return None
        name, sig_rest = m.group(1), m.group(2)
        desc = ""
        if "#" in sig_rest:
            sig_rest, desc = sig_rest.rsplit("#", 1)
            desc = desc.strip()
        sig = sig_rest.split(": ...")[0].strip()
        return TypeInfo(
            name=name, kind="function",
            docstring=desc,
            members=[Member(name=name, kind="method", signature=sig, description=desc)],
        )

    name, sig, desc = m.group(1), m.group(2), m.group(3) or ""
    return TypeInfo(
        name=name, kind="function",
        docstring=desc,
        members=[Member(name=name, kind="method", signature=sig, description=desc)],
    )


def _parse_class(lines: List[str], start: int, section: str) -> Tuple[Optional[TypeInfo], int]:
    """Parse a class definition starting at the given line index."""
    line = lines[start]
    m = re.match(r"class (\w+)(?:\((\w+)\))?:", line)
    if not m:
        return None, start + 1

    name = m.group(1)
    base = m.group(2) or ""
    kind = section if section in ("enum", "struct", "class") else "class"

    info = TypeInfo(name=name, kind=kind, base=base)

    i = start + 1
    # Parse class body (indented lines)
    in_docstring = False
    docstring_lines: List[str] = []
    pending_property = False

    while i < len(lines):
        raw = lines[i]
        # Join continuation lines (e.g. "def foo() -> Type\n: ...")
        if not in_docstring and raw.startswith("    ") and not raw.strip().startswith(('"""', 'r"""')):
            while (i + 1 < len(lines)
                   and not raw.rstrip().endswith(": ...")
                   and not raw.rstrip().endswith('"""')
                   and not raw.strip() == "..."
                   and not raw.strip() == ""
                   and not raw.strip() == "@property"
                   and lines[i + 1].startswith("    ")
                   and not lines[i + 1].strip().startswith(("def ", "class ", "@", '"""', 'r"""'))):
                i += 1
                raw = raw.rstrip() + lines[i].strip()
            # Also join if next line is just ": ..." or ": ...  # comment"
            if (i + 1 < len(lines)
                    and re.match(r"^: \.\.\.(\s*#.*)?$", lines[i + 1].strip())):
                i += 1
                raw = raw.rstrip() + lines[i].strip()
        if not raw.startswith("    ") and raw.strip() != "" and not in_docstring:
            break
        if raw.strip() == "":
            if not in_docstring:
                i += 1
                # An empty line after unindented content means end of class
                if i < len(lines) and not lines[i].startswith("    "):
                    break
                continue
            else:
                docstring_lines.append("")
                i += 1
                continue

        stripped = raw.strip()

        # Docstring body/close must be checked BEFORE opener detection,
        # otherwise `"""` on its own is mistaken for a new docstring start.
        if in_docstring:
            if '"""' in stripped:
                before = stripped.split('"""')[0]
                if before:
                    docstring_lines.append(before)
                info.docstring = "\n".join(docstring_lines).strip()
                _extract_module(info, info.docstring)
                docstring_lines = []
                in_docstring = False
                i += 1
                continue
            else:
                docstring_lines.append(stripped)
                i += 1
                continue

        # Docstring opener (only when not already inside one)
        if stripped.startswith('r"""') or stripped.startswith('"""'):
            prefix = 'r"""' if stripped.startswith('r"""') else '"""'
            rest = stripped[len(prefix):]
            if rest.endswith('"""') and len(rest) > 3:
                # Single-line docstring
                info.docstring = rest[:-3].strip()
                _extract_module(info, info.docstring)
                i += 1
                continue
            elif rest.endswith('"""'):
                info.docstring = rest[:-3].strip()
                _extract_module(info, info.docstring)
                i += 1
                continue
            else:
                in_docstring = True
                if rest:
                    docstring_lines.append(rest)
                i += 1
                continue

        # @property decorator
        if stripped == "@property":
            pending_property = True
            i += 1
            continue

        # Property definition
        if pending_property and stripped.startswith("def "):
            pending_property = False
            pm = re.match(
                r"def (\w+)\(self\)\s*->\s*([\w\[\], ]+):\s*\.\.\.(?:\s*#\s*(.*))?",
                stripped,
            )
            if pm:
                info.members.append(Member(
                    name=pm.group(1),
                    kind="property",
                    return_type=pm.group(2).strip(),
                    description=pm.group(3).strip() if pm.group(3) else "",
                ))
            i += 1
            continue

        # Method definition
        if stripped.startswith("def "):
            mm = re.match(
                r"def (\w+)(\(.*?\))(?:\s*->.*?)?\s*:\s*\.\.\.(?:\s*#\s*(.*))?",
                stripped,
            )
            if mm:
                info.members.append(Member(
                    name=mm.group(1),
                    kind="method",
                    signature=mm.group(2),
                    description=mm.group(3).strip() if mm.group(3) else "",
                ))
            i += 1
            continue

        # Enum member: NAME: ClassName = ...  # value: desc
        if kind == "enum" and ": " in stripped and "= ..." in stripped:
            em = re.match(
                r"(\w+):\s*\w+\s*=\s*\.\.\.(?:\s*#\s*(.*))?",
                stripped,
            )
            if em:
                val_desc = em.group(2) or ""
                val = ""
                desc = val_desc
                if ":" in val_desc:
                    val, desc = val_desc.split(":", 1)
                    val = val.strip()
                    desc = desc.strip()
                info.members.append(Member(
                    name=em.group(1),
                    kind="enum_value",
                    value=val,
                    description=desc,
                ))
            i += 1
            continue

        # Ellipsis placeholder for empty classes
        if stripped == "...":
            i += 1
            continue

        i += 1

    return info, i


def _extract_module(info: TypeInfo, docstring: str) -> None:
    """Extract C++ module name from docstring."""
    m = re.search(r"\*\*Module:\*\*\s*(\w+)", docstring)
    if m:
        info.module = m.group(1)
    else:
        m = re.search(r"- \*\*Module\*\*\s*\S+\s*(\w+)", docstring)
        if m:
            info.module = m.group(1)


# ---------------------------------------------------------------------------
# Module classification
# ---------------------------------------------------------------------------

# Map name prefixes / keywords to human-readable domain categories
DOMAIN_RULES: List[Tuple[str, str]] = [
    # Fortnite-specific
    ("Fort", "Fortnite"),
    ("Athena", "Fortnite"),
    ("Creative", "Fortnite Creative"),
    ("Playlist", "Fortnite"),
    # Editor subsystems
    ("EditorAsset", "Asset Pipeline"),
    ("AssetTool", "Asset Pipeline"),
    ("AssetRegistry", "Asset Pipeline"),
    ("EditorActor", "Actors & Levels"),
    ("EditorLevel", "Actors & Levels"),
    ("LevelEditor", "Actors & Levels"),
    ("EditorFilter", "Actors & Levels"),
    ("EditorValidator", "Validation"),
    ("MaterialEditing", "Materials"),
    ("Material", "Materials"),
    ("StaticMeshEditor", "Static Meshes"),
    ("StaticMesh", "Static Meshes"),
    ("GeometryScript", "Geometry Scripting"),
    ("PCG", "PCG (Procedural Content Generation)"),
    ("MovieGraph", "Rendering (Movie Pipeline)"),
    ("MoviePipeline", "Rendering (Movie Pipeline)"),
    ("MovieRender", "Rendering (Movie Pipeline)"),
    ("MovieScene", "Sequencer & Cinematics"),
    ("LevelSequence", "Sequencer & Cinematics"),
    ("Sequencer", "Sequencer & Cinematics"),
    ("TakeRecorder", "Sequencer & Cinematics"),
    ("Niagara", "Niagara VFX"),
    ("Audio", "Audio & MetaSound"),
    ("Sound", "Audio & MetaSound"),
    ("MetaSound", "Audio & MetaSound"),
    ("Quartz", "Audio & MetaSound"),
    ("Anim", "Animation"),
    ("Skeleton", "Animation"),
    ("InputAction", "Enhanced Input"),
    ("InputMapping", "Enhanced Input"),
    ("EnhancedInput", "Enhanced Input"),
    ("Widget", "UI / UMG"),
    ("UMG", "UI / UMG"),
    ("EditorUtilityWidget", "UI / UMG"),
    ("Chaos", "Physics"),
    ("Destruction", "Physics"),
    ("Landscape", "Landscape"),
    ("Automation", "Testing & Screenshots"),
    ("Screenshot", "Testing & Screenshots"),
    ("DataTable", "Data Tables & Curves"),
    ("CurveTable", "Data Tables & Curves"),
    ("GameplayTag", "Data Tables & Curves"),
    ("Interchange", "Interchange (Import/Export)"),
    ("Texture", "Textures"),
    ("Skeletal", "Skeletal Meshes"),
    ("Blueprint", "Blueprints"),
    ("SubobjectData", "Blueprints"),
    ("Enum", "Core / Base Types"),
    ("Struct", "Core / Base Types"),
    ("Vector", "Math"),
    ("Rotator", "Math"),
    ("Transform", "Math"),
    ("Quat", "Math"),
    ("Matrix", "Math"),
    ("Color", "Math"),
    ("LinearColor", "Math"),
    ("Box", "Math"),
    ("Plane", "Math"),
    ("Ray", "Math"),
]


def classify_type(info: TypeInfo) -> str:
    """Assign a domain category to a type based on name and module."""
    name = info.name

    # Check module first
    if info.module:
        mod = info.module
        if "Niagara" in mod:
            return "Niagara VFX"
        if "PCG" in mod:
            return "PCG (Procedural Content Generation)"
        if "GeometryScript" in mod:
            return "Geometry Scripting"

    # Check name prefix rules
    for prefix, domain in DOMAIN_RULES:
        if name.startswith(prefix):
            return domain

    # Fallback heuristics
    if info.base:
        for prefix, domain in DOMAIN_RULES:
            if info.base.startswith(prefix):
                return domain

    return "Other"


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------


def generate_docs(types: List[TypeInfo], metadata: Dict[str, str], output_dir: str) -> None:
    """Generate markdown documentation files from parsed types."""
    os.makedirs(output_dir, exist_ok=True)

    # Classify types into domains
    domains: Dict[str, List[TypeInfo]] = {}
    functions: List[TypeInfo] = []

    for t in types:
        if t.kind == "function":
            functions.append(t)
            continue
        domain = classify_type(t)
        domains.setdefault(domain, [])
        domains[domain].append(t)

    # Sort domains by type count descending, but keep "Other" last
    sorted_domains = sorted(
        domains.items(),
        key=lambda x: (x[0] == "Other", -len(x[1])),
    )

    # Stats
    total_types = len(types)
    total_classes = sum(1 for t in types if t.kind == "class")
    total_enums = sum(1 for t in types if t.kind == "enum")
    total_structs = sum(1 for t in types if t.kind == "struct")
    total_functions = len(functions)

    # --- Generate README.md (index) ---
    readme_lines = [
        "# UEFN Python API Documentation",
        "",
        "> Auto-generated from `.pyi` stub via `tools/generate_api_docs.py`",
        "",
        f"**{total_types:,} types** — "
        f"{total_classes:,} classes, {total_enums:,} enums, "
        f"{total_structs:,} structs, {total_functions:,} functions",
        "",
        "---",
        "",
        "## Domains",
        "",
        "| Domain | Classes | Enums | Structs | Total | File |",
        "|--------|---------|-------|---------|-------|------|",
    ]

    for domain, dtypes in sorted_domains:
        fname = _domain_filename(domain)
        nc = sum(1 for t in dtypes if t.kind == "class")
        ne = sum(1 for t in dtypes if t.kind == "enum")
        ns = sum(1 for t in dtypes if t.kind == "struct")
        readme_lines.append(
            f"| {domain} | {nc} | {ne} | {ns} | {len(dtypes)} | [{fname}]({fname}) |"
        )

    if functions:
        readme_lines.append(
            f"| Top-level Functions | — | — | — | {len(functions)} | "
            f"[functions.md](functions.md) |"
        )

    readme_lines.extend(["", "---", ""])

    _write_file(os.path.join(output_dir, "README.md"), "\n".join(readme_lines))

    # --- Generate per-domain files ---
    for domain, dtypes in sorted_domains:
        fname = _domain_filename(domain)
        content = _generate_domain_doc(domain, dtypes)
        _write_file(os.path.join(output_dir, fname), content)

    # --- Generate functions file ---
    if functions:
        content = _generate_functions_doc(functions)
        _write_file(os.path.join(output_dir, "functions.md"), content)

    print(f"Generated {len(sorted_domains) + 2} files in {output_dir}/")
    print(f"  README.md (index)")
    print(f"  {len(sorted_domains)} domain files")
    if functions:
        print(f"  functions.md ({len(functions)} functions)")


def _domain_filename(domain: str) -> str:
    """Convert domain name to a safe filename."""
    name = domain.lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    name = name.strip("_")
    return f"{name}.md"


def _generate_domain_doc(domain: str, types: List[TypeInfo]) -> str:
    """Generate markdown for a single domain."""
    lines = [
        f"# {domain}",
        "",
        f"> {len(types)} types",
        "",
    ]

    # Separate by kind
    enums = [t for t in types if t.kind == "enum"]
    structs = [t for t in types if t.kind == "struct"]
    classes = [t for t in types if t.kind == "class"]

    # Summary table
    top_classes = sorted(classes, key=lambda t: len(t.members), reverse=True)[:10]
    if top_classes:
        lines.append("**Key entry points:**")
        entries = [f"`{t.name}` ({len(t.members)} members)" for t in top_classes]
        lines.append(", ".join(entries))
        lines.extend(["", "---", ""])

    # Classes
    if classes:
        lines.append(f"## Classes ({len(classes)})")
        lines.append("")
        for t in sorted(classes, key=lambda x: x.name):
            lines.extend(_format_type(t))

    # Structs
    if structs:
        lines.append(f"## Structs ({len(structs)})")
        lines.append("")
        for t in sorted(structs, key=lambda x: x.name):
            lines.extend(_format_type(t))

    # Enums
    if enums:
        lines.append(f"## Enums ({len(enums)})")
        lines.append("")
        for t in sorted(enums, key=lambda x: x.name):
            lines.extend(_format_type(t))

    return "\n".join(lines)


def _format_type(t: TypeInfo) -> List[str]:
    """Format a single type as markdown."""
    lines = []
    header = f"### `{t.name}`"
    if t.base:
        header += f" (extends `{t.base}`)"
    lines.append(header)
    lines.append("")

    if t.docstring:
        # Clean up docstring for markdown
        doc = t.docstring.replace("r\"\"\"", "").replace('"""', "").strip()
        if doc:
            lines.append(f"> {doc}")
            lines.append("")

    properties = [m for m in t.members if m.kind == "property"]
    methods = [m for m in t.members if m.kind == "method"]
    enum_values = [m for m in t.members if m.kind == "enum_value"]

    if enum_values:
        lines.append("**Values:**")
        lines.append("")
        lines.append("| Name | Value | Description |")
        lines.append("|------|-------|-------------|")
        for m in enum_values:
            lines.append(f"| `{m.name}` | {m.value} | {m.description} |")
        lines.append("")

    if properties:
        lines.append("**Properties:**")
        lines.append("")
        lines.append("| Name | Type | Description |")
        lines.append("|------|------|-------------|")
        for m in properties:
            lines.append(f"| `{m.name}` | `{m.return_type}` | {m.description} |")
        lines.append("")

    if methods:
        lines.append("**Methods:**")
        lines.append("")
        for m in methods:
            desc = f" — {m.description}" if m.description else ""
            lines.append(f"- `{m.name}{m.signature}`{desc}")
        lines.append("")

    if not enum_values and not properties and not methods:
        lines.append("*No documented members.*")
        lines.append("")

    lines.append("---")
    lines.append("")
    return lines


def _generate_functions_doc(functions: List[TypeInfo]) -> str:
    """Generate markdown for top-level functions."""
    lines = [
        "# Top-level Functions",
        "",
        f"> {len(functions)} functions available on the `unreal` module",
        "",
        "| Function | Description |",
        "|----------|-------------|",
    ]

    for f in sorted(functions, key=lambda x: x.name):
        member = f.members[0] if f.members else None
        if member:
            sig = f"`{f.name}{member.signature}`"
            desc = member.description or ""
        else:
            sig = f"`{f.name}()`"
            desc = ""
        lines.append(f"| {sig} | {desc} |")

    lines.append("")
    return "\n".join(lines)


def _write_file(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate markdown API docs from a UEFN .pyi stub"
    )
    parser.add_argument(
        "--stub", required=True,
        help="Path to the .pyi stub file (generated by generate_uefn_stub.py)",
    )
    parser.add_argument(
        "--output", default="docs/generated",
        help="Output directory for generated docs (default: docs/generated)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.stub):
        print(f"Error: stub file not found: {args.stub}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing stub: {args.stub}")
    types, metadata = parse_stub(args.stub)
    print(f"Parsed {len(types)} types")

    if not types:
        print("Warning: no types found in stub file. Is it a valid .pyi?", file=sys.stderr)
        sys.exit(1)

    generate_docs(types, metadata, args.output)
    print("Done.")


if __name__ == "__main__":
    main()
